/**
 * FakeLlm — deterministic drafts, no network.
 *
 * Selected when no LLM key is configured. Same purpose as FakeProvider: the
 * whole draft → approve → queue → publish loop, including the auto-approve
 * timer, has to be exercisable thousands of times without spending credits or
 * posting anything. The pacing and approval logic is what needs testing here,
 * not the prose.
 */

import type {
  AuthorContext,
  CommentDraft,
  KeywordSuggestion,
  LlmProvider,
  PostDraft,
  SourcePost,
} from '../llm.js';

export interface FakeLlmOptions {
  log?: (msg: string) => void;
  /** Make draftComment decline, to exercise the "not worth commenting" path. */
  declineComments?: boolean;
}

export class FakeLlm implements LlmProvider {
  readonly name = 'fake';
  readonly model = 'fake-model';

  readonly calls: { method: string; input: unknown }[] = [];
  private readonly log: (msg: string) => void;
  private readonly declineComments: boolean;

  constructor(options: FakeLlmOptions = {}) {
    this.log = options.log ?? ((msg) => console.log(`[fake-llm] ${msg}`));
    this.declineComments = options.declineComments ?? false;
  }

  private record(method: string, input: unknown): void {
    this.calls.push({ method, input });
    this.log(method);
  }

  async suggestKeywords(input: { author: AuthorContext }): Promise<KeywordSuggestion[]> {
    this.record('suggestKeywords', input);
    // Derived from the headline so the output at least tracks the input.
    const words = (input.author.headline ?? '')
      .split(/[|,]/)
      .map((w) => w.trim())
      .filter((w) => w.length > 2 && w.length < 30)
      .slice(0, 5);
    return words.map((term) => ({
      term,
      reason: `Appears in your headline.`,
    }));
  }

  async draftPost(input: {
    author: AuthorContext;
    trending: SourcePost[];
    foldCharLimit: number;
  }): Promise<PostDraft> {
    this.record('draftPost', { trending: input.trending.length });
    const top = input.trending[0];
    const hook = top
      ? `Everyone is talking about ${top.keyword} this week.`
      : 'A thought on the work.';
    return {
      text:
        `${hook}\n\n` +
        `This is a fake draft written without calling a model, so the pacing ` +
        `and approval flow can be tested end to end.\n\n` +
        `Nothing here was generated by an LLM.`,
      rationale: top
        ? `Top post for "${top.keyword}" had ${top.reactions} reactions.`
        : 'No trending posts available.',
    };
  }

  async draftComment(input: {
    author: AuthorContext;
    post: SourcePost;
    maxChars: number;
  }): Promise<CommentDraft> {
    this.record('draftComment', { author: input.post.authorName });
    if (this.declineComments) {
      return {
        text: '',
        rationale: 'Injected decline — post judged a poor fit.',
        worthCommenting: false,
      };
    }
    const first = input.post.authorName.split(/\s+/)[0] ?? 'there';
    return {
      text: `${first} — fake comment for testing. No model was called.`.slice(
        0,
        input.maxChars,
      ),
      rationale: `Matched keyword "${input.post.keyword}".`,
      worthCommenting: true,
    };
  }
}
